services:
  db:
    image: postgres:16-alpine
    container_name: pazaak3
    environment:
      POSTGRES_DB: pazaak3_db
      POSTGRES_USER: pazaak3_db
      POSTGRES_PASSWORD: pazaak3_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  redis:
    image: redis:7-alpine
    container_name: pazaak_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
